<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.fw</groupId>
        <artifactId>KnowGo-business</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>KnowGo-order</artifactId>
    <packaging>jar</packaging>

    <name>KnowGo-order</name>
    <description>订单模块</description>

    <properties>
        <application.name>KnwoGo-goods</application.name>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.fw</groupId>
            <artifactId>KnowGo-datasource</artifactId>
        </dependency>

        <dependency>
            <groupId>com.fw</groupId>
            <artifactId>KnowGo-limiter</artifactId>
        </dependency>

        <dependency>
            <groupId>com.fw</groupId>
            <artifactId>KnowGo-api</artifactId>
        </dependency>

        <dependency>
            <groupId>com.fw</groupId>
            <artifactId>KnowGo-rpc</artifactId>
        </dependency>

        <dependency>
            <groupId>com.fw</groupId>
            <artifactId>KnowGo-config</artifactId>
        </dependency>

        <dependency>
            <groupId>com.fw</groupId>
            <artifactId>KnowGo-skywalking</artifactId>
        </dependency>

        <dependency>
            <groupId>com.fw</groupId>
            <artifactId>KnowGo-order-client</artifactId>
        </dependency>

        <dependency>
            <groupId>com.fw</groupId>
            <artifactId>KnowGo-tcc</artifactId>
        </dependency>
    </dependencies>
</project>
