openapi: 3.0.0
info:
  title: 文档服务 API
  description: 提供文档上传和查询功能的API接口
  version: 1.0.0
paths:
  /document/upload:
    post:
      summary: 上传文档
      description: 上传文档文件并提取内容到向量数据库
      operationId: uploadDocument
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: 要上传的文档文件
      responses:
        '200':
          description: 上传成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResultBoolean'
        '400':
          description: 请求参数错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
  /document/query:
    get:
      summary: 查询文档
      description: 根据查询字符串搜索相关文档
      operationId: queryDocument
      parameters:
        - name: query
          in: query
          required: true
          schema:
            type: string
          description: 查询字符串
      responses:
        '200':
          description: 查询成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResultDocumentList'
components:
  schemas:
    ResultBoolean:
      type: object
      properties:
        code:
          type: string
          description: 状态码
        success:
          type: boolean
          description: 是否成功
        message:
          type: string
          description: 消息描述
        data:
          type: boolean
          description: 上传结果，true表示成功
    ResultDocumentList:
      type: object
      properties:
        code:
          type: string
          description: 状态码
        success:
          type: boolean
          description: 是否成功
        message:
          type: string
          description: 消息描述
        data:
          type: array
          items:
            $ref: '#/components/schemas/Document'
    Document:
      type: object
      description: Spring AI Document类，包含文档内容和元数据
      properties:
        id:
          type: string
          description: 文档唯一标识
        content:
          type: string
          description: 文档内容
        metadata:
          type: object
          description: 文档元数据
          additionalProperties: {}
    ErrorResult:
      type: object
      properties:
        code:
          type: string
          description: 错误码
        success:
          type: boolean
          description: 是否成功，错误时为false
        message:
          type: string
          description: 错误信息
        data:
          type: null
          description: 错误时数据为null